# Generated by Django 3.0.8 on 2020-07-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200720_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='active_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_modified_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='slug',
        ),
    ]
