# Generated by Django 3.0.8 on 2020-07-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('employee', '0002_auto_20200720_2153'),
    ]

    operations = [
    ]
